version: '2'
services:
  odoo-web:
    image: ubuntu:18.04
    container_name: odoo-web
    links:
      - odoo-db:db
    depends_on:
      - odoo-db
    ports:
      - "8069:8069"
      - "80:80"
      - "443:443"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    stdin_open: true
    tty: true
  odoo-db:
    image: postgres:10
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo-admin
      - POSTGRES_USER=odoo-admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
